// constants/boardMembers.js
export const boardMembersChief = [
  { post: "President",             fullName: "Vishwajeet Pawar",    imgUrl: "/assets/president.png" },
  { post: "Vice President",        fullName: "Prasad Bedage",      imgUrl: "/assets/vp.png"        },
  { post: "Secretary",             fullName: "Pranav Patil",       imgUrl: "/assets/sec.png"       },
  { post: "Chief PDE",             fullName: "Haripriya Yele",     imgUrl: "/assets/pde3.png"       },
  { post: "Chief PDE",             fullName: "Samruddhi Shinde",   imgUrl: "/assets/pde2.png"      },
  { post: "Chief PDE",             fullName: "Gayatri Patil",      imgUrl: "/assets/pde4.png"      },
  { post: "Chief PDE",             fullName: "Samarth Gaikwad",    imgUrl: "/assets/pde.png"      },
  { post: "Chief PDF",             fullName: "Chinmayi Bargale",   imgUrl: "/assets/pdf.png"       },
  { post: "Chief PDF",             fullName: "Prasad Bedage",      imgUrl: "/assets/vp.png"       },
  { post: "Chief PDP",             fullName: "Juhi Zinage",        imgUrl: "/assets/pdp.png"       },
  { post: "Chief PDP",             fullName: "Sahil Badera",       imgUrl: "/assets/pdp2.png"      },
  { post: "Chief PDP",             fullName: "Sakshi Mehtre",      imgUrl: "/assets/pdp4.png"      },
  { post: "Chief PDP",             fullName: "Anchit Bagde",       imgUrl: "/assets/pdp3.png"      },
  { post: "Chief Skid-P",          fullName: "Piyush Dawkhare",    imgUrl: "/assets/skidp.png"     },
  { post: "Chief Skid-P",          fullName: "Manisha Shinde",     imgUrl: "/assets/skid6p2.png"    },
  { post: "Chief Skid-P",          fullName: "Dhanshri Mali",      imgUrl: "/assets/skidp.png"     },
  { post: "Chief Skid-P",          fullName: "Pratik Kapre",       imgUrl: "/assets/skidp2.png"    },
  { post: "Chief Skid-W",          fullName: "Samruddhi Shinde",   imgUrl: "/assets/pdf.png"       },
  { post: "Creative Team Head",    fullName: "Rajvardhan Kadam",   imgUrl: "/assets/CTH.png"       },
  { post: "Creative Team Head",    fullName: "Chaitrali Jadhav",   imgUrl: "/assets/CTH2.png"      },
  { post: "Creative Team Head",    fullName: "Tanuja Beskar",      imgUrl: "/assets/CTH3.png"      },
  { post: "Chief Aptitude Developer", fullName: "Darshan Nandurge", imgUrl: "/assets/aptidev.png"   },
  { post: "Chief Web Developer",   fullName: "Haripriya Yele",     imgUrl: "/assets/pdf.png"       },
  { post: "Chief Web Developer",   fullName: "Piyush Dawkhare",    imgUrl: "/assets/pdf.png"       },
  { post: "Chief PACEr",           fullName: "Kalpesh Kamble",     imgUrl: "/assets/5pdf.png"       },
];