// constants/boardMembers.js
export const boardMembersChief = [
  { post: "President",                         fullName: "Vishwajeet Pawar",   imgUrl: "/assets/Cheif_Board/Vishvajeet_Pawar.jpg" },
  { post: "Vice President & Chief PDF",        fullName: "Prasad Bedage",      imgUrl: "/assets/Cheif_Board/Prasad_Bedage.png"},
  { post: "Secretary",                         fullName: "Pranav Patil",       imgUrl: "/assets/Cheif_Board/Pranav_Patil.jpg" },
  { post: "Chief PDE & Chief Web Developer",   fullName: "Haripriya Yele",     imgUrl: "/assets/Cheif_Board/Haripriya_Yele.png"},
  { post: "Chief PDE & Chief Skid-W",          fullName: "Samruddhi Shinde",   imgUrl: "/assets/Cheif_Board/Samruddhi_Shinde.jpg"},
  { post: "Chief PDE",                         fullName: "Gayatri Patil",      imgUrl: "/assets/Cheif_Board/Gayatri_Patil.jpg"      },
  { post: "Chief PDE",                         fullName: "Samarth Gaikwad",    imgUrl: "/assets/Cheif_Board/Samarth_Gaikwad0.png"      },
  { post: "Chief PDF",                         fullName: "Chinmayi Bargale",   imgUrl: "/assets/Cheif_Board/Chinmayi_Bargale.JPG"       },
  //{ post: "Chief PDF",                         fullName: "Prasad Bedage",      imgUrl: "/assets/Cheif_Board/Prasad_Bedage.jpg"       },
  { post: "Chief PDP",                         fullName: "Juhi Zinage",        imgUrl: "/assets/Cheif_Board/Juhi_Zinage.png"       },
  { post: "Chief PDP",                         fullName: "Sahil Badera",       imgUrl: "/assets/Cheif_Board/Sahil_Badera.png"      },
  { post: "Chief PDP",                         fullName: "Sakshi Mehtre",      imgUrl: "/assets/Cheif_Board/Sakshi_Mehtre0.png"      },
  { post: "Chief PDP",                         fullName: "Anchit Bagde",       imgUrl: "/assets/Cheif_Board/Anchit_Bagde.jpg"      },
  { post: "Chief Skid-P & Chief Web Developer",fullName: "Piyush Dawkhare",    imgUrl: "/assets/Cheif_Board/Piyush_Dawkhare.png"     },
  { post: "Chief Skid-P",                      fullName: "Manisha Shinde",     imgUrl: "/assets/Cheif_Board/Manisha_Shinde.jpg"    },
  { post: "Chief Skid-P",                      fullName: "Dhanshri Mali",      imgUrl: "/assets/Cheif_Board/Dhanshri_Mali.jpg"     },
  { post: "Chief Skid-P",                      fullName: "Pratik Kapre",       imgUrl: "/assets/Cheif_Board/Pratik_Kapre.jpg"    },
  //{ post: "Chief Skid-W",                      fullName: "Samruddhi Shinde",   imgUrl: "/assets/Cheif_Board/Samruddhi_Shinde.jpg"       },
  { post: "Creative Team Head",                fullName: "Rajvardhan Kadam",   imgUrl: "/assets/Cheif_Board/Rajvardhan_Kadam.png"       },
  { post: "Creative Team Head",                fullName: "Chaitrali Jadhav",   imgUrl: "/assets/Cheif_Board/Chaitrali_Jadhav.jpg"      },
  { post: "Creative Team Head",                fullName: "Tanuja Beskar",      imgUrl: "/assets/Cheif_Board/Tanuja_Beskar.png"      },
  { post: "Chief Aptitude Developer",          fullName: "Darshan Nandurge", imgUrl: "/assets/Cheif_Board/Darshan_Nandurge.jpg"   },
  //{ post: "Chief Web Developer",               fullName: "Haripriya Yele",     imgUrl: "/assets/Cheif_Board/Haripriya_Yele.jpg"       },
  //{ post: "Chief Web Developer",               fullName: "Pyush Dawkhare",    imgUrl: "/assets/Cheif_Board/Piyush_Dawkhare.png"       },
  { post: "Chief PACEr",                       fullName: "Kalpesh Kamble",     imgUrl: "/assets/Cheif_Board/Kalpesh_Kamble.jpg"       },
];